# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vision.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvision.proto\x12\revofab.vision\"*\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"4\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"g\n\x0f\x41nalysisRequest\x12)\n\x0b\x63olor_image\x18\x01 \x01(\x0b\x32\x14.evofab.vision.Image\x12)\n\x0b\x64\x65pth_image\x18\x02 \x01(\x0b\x32\x14.evofab.vision.Image\"\xbb\x01\n\x10\x41nalysisResponse\x12\x16\n\x0emean_curvature\x18\x01 \x01(\x01\x12\x15\n\rmax_curvature\x18\x02 \x01(\x01\x12-\n\rspline_points\x18\x03 \x03(\x0b\x32\x16.evofab.vision.Point3D\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0c\n\x04mask\x18\x05 \x01(\x0c\x12\x15\n\rmask_coverage\x18\x06 \x01(\x02\x12\x14\n\x0cproc_time_ms\x18\x07 \x01(\x02\x32z\n\x15VisionAnalysisService\x12\x61\n\x1a\x41nalyzeActuatorPerformance\x12\x1e.evofab.vision.AnalysisRequest\x1a\x1f.evofab.vision.AnalysisResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINT3D']._serialized_start=31
  _globals['_POINT3D']._serialized_end=73
  _globals['_IMAGE']._serialized_start=75
  _globals['_IMAGE']._serialized_end=127
  _globals['_ANALYSISREQUEST']._serialized_start=129
  _globals['_ANALYSISREQUEST']._serialized_end=232
  _globals['_ANALYSISRESPONSE']._serialized_start=235
  _globals['_ANALYSISRESPONSE']._serialized_end=422
  _globals['_VISIONANALYSISSERVICE']._serialized_start=424
  _globals['_VISIONANALYSISSERVICE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
