# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vision_pb2 as vision__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisionAnalysisServiceStub(object):
    """The main service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeActuatorPerformance = channel.stream_stream(
                '/evofab.vision.VisionAnalysisService/AnalyzeActuatorPerformance',
                request_serializer=vision__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=vision__pb2.AnalysisResponse.FromString,
                _registered_method=True)


class VisionAnalysisServiceServicer(object):
    """The main service definition.
    """

    def AnalyzeActuatorPerformance(self, request_iterator, context):
        """Analyzes a real-time stream of camera data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeActuatorPerformance': grpc.stream_stream_rpc_method_handler(
                    servicer.AnalyzeActuatorPerformance,
                    request_deserializer=vision__pb2.AnalysisRequest.FromString,
                    response_serializer=vision__pb2.AnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evofab.vision.VisionAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evofab.vision.VisionAnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisionAnalysisService(object):
    """The main service definition.
    """

    @staticmethod
    def AnalyzeActuatorPerformance(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/evofab.vision.VisionAnalysisService/AnalyzeActuatorPerformance',
            vision__pb2.AnalysisRequest.SerializeToString,
            vision__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
